version: '3'
services:
  api:
    build: ./graphql-app
    ports:
      - '3000:3000'
    links:
      - db
    container_name: graphql-api
  client:
    build: ./todo-app
    ports:
      - '4200:80'
    container_name: graphql-client
  db:
    build: ./mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/data:/data/db
    container_name: todo-db
